# Generated by Django 4.0.4 on 2022-05-05 18:18

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.Post.file_path),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, max_length=24),
        ),
    ]
